name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build snap
        id: build-snap
        uses: snapcore/action-build@master
      - name: Install snap
        run: sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}
      - name: Test PlantUML CLI
        run: |
          plantuml --version
          plantuml --check-graphviz
          plantuml --svg tests/*.puml

      - name: Verify SVG output
        run: |
          if [ ! -f tests/license.svg ]; then
            echo "SVG output file not found!"
            exit 1
          fi

          echo "SVG output file generated successfully."
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: snap-package
          path: |
            *.snap
            tests/*.svg
